name: project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
- python=3.7
- pytorch
- cudatoolkit=11.3
- torchvision
- pytorch-lightning
- matplotlib
- seaborn
- scikit-image
- scipy
- torchinfo
- scikit-learn
- pip:
  - ipykernel
  - ipywidgets
  - IProgress
  - opencv-python
  - Pillow
  - tqdm
  - torchio 